services:
  # database
  database:
    container_name: database
    ports:
      - "5432:5432"
    build:
      context: ./database
      dockerfile: Dockerfile

  # backend
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "
        python manage.py migrate &&
        scripts/create_superuser.sh &&
        python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  # frontend
  frontend:
    container_name: frontend
    build:
      context: ./frontend/app
      dockerfile: ../Dockerfile
      args:
        REACT_APP_BACKEND_API_PROTOCOL: ${REACT_APP_BACKEND_API_PROTOCOL}
        REACT_APP_BACKEND_API_HOST_NAME: ${REACT_APP_BACKEND_API_HOST_NAME}
        REACT_APP_BACKEND_API_PORT: ${REACT_APP_BACKEND_API_PORT}
    restart: always
    ports:
      - "80:80"
