# 参考
# https://github.com/Azure/arm-deploy
# https://github.com/Azure/cli

name: Azure Bicep Deployment.

# トリガーを指定
on:
  # プッシュ
  push:
    branches:
      - main
      - develop
    paths:
      - "infra/**"

  # 手動
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

# 環境変数（環境依存なし）
env:
  # Azure
  APP_NAME: ${{ vars.APP_NAME }}
  SUFFIX: ${{ vars.SUFFIX }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    # 環境選択
    environment: ${{ github.ref_name == 'main' && 'Production' || github.ref_name == 'develop' && 'Development'}}

    # 環境変数（環境依存）
    env:
      # Azure
      APP_ENVIRONMENT: ${{ vars.APP_ENVIRONMENT }}
      # Backend and Database
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DJANGO_ALLOWED_HOSTS: ${{ vars.DJANGO_ALLOWED_HOSTS }}
      DJANGO_CSRF_TRUSTED_ORIGINS: ${{ vars.DJANGO_CSRF_TRUSTED_ORIGINS }}
      DJANGO_SUPERUSER_USERNAME: ${{ vars.DJANGO_SUPERUSER_USERNAME }}
      DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
      DJANGO_SUPERUSER_EMAIL: ${{ vars.DJANGO_SUPERUSER_EMAIL }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
      DJANGO_CORS_ALLOWED_ORIGINS: ${{ vars.DJANGO_CORS_ALLOWED_ORIGINS}}
      PYTHONUNBUFFERED: ${{ vars.PYTHONUNBUFFERED}}
      # Frontend
      REACT_APP_BACKEND_API_HOST_NAME: ${{ vars.REACT_APP_BACKEND_API_HOST_NAME }}
      REACT_APP_BACKEND_API_PORT: ${{ vars.REACT_APP_BACKEND_API_PORT }}

    steps:
      # タイムスタンプ生成
      - name: Generate timestamp
        env:
          TZ: "Asia/Tokyo"
        run: echo "TIMESTAMP=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV

      # チェックアウト
      - name: Checkout to the branch
        uses: actions/checkout@v4

      # Azure ログイン
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # リソースデプロイ
      - name: Deploy with Azure Bicep
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az deployment group create \
              --name Deploy-${{ env.APP_NAME }}_${{ env.TIMESTAMP }} \
              --resource-group ${{ vars.AZURE_RESOURCE_GROUP_NAME }} \
              --template-file infra/main.bicep \
              --parameters infra/main.bicepparam
